### PR TITLE
Chicago crime tensor

### PR DESCRIPTION
**Pull request by ShadenSmith**

### CODE REVIEW

**Review by jeewhanchoi — COMMENTED** [review]
Added a sentence to clarify the DOMESTIC VIOLENCE data point.
Also, I think it would be nice to have the statistics for the latitude-longitude tensor as well.

**Comment by ShadenSmith** [comment]
Great, thanks!

**Comment by fruitfly1026** [comment]
Thanks Shaden. Maybe we can add a subtitle "# Processing (or other words)" to specify the detailed tensor processing information. Also, put this after "Tensor statistics and downloadable files", I think some people don't care too much how we generate the tensors. 
I think for now, "tensor statistics" describes the highest order of the generated tensors, so should be 5th-order one. But we're thinking of separating tensors from the same data, so never mind.

**Comment by ShadenSmith** [comment]
That's a good plan. We should add it to the main tensor template (`_layouts/tensor_layout.html`).

**Pull request merged**
