### PR TITLE
adds paragraph about tensor parsing

### PR DESCRIPTION
**Pull request by ShadenSmith**

### CODE REVIEW

**Comment by ShadenSmith** [comment]
Merging.

**Review by jeewhanchoi — COMMENTED** [review]
Sounds good.
Also, we should probably come up with an initial list of data types (binary, count, etc.) and have an option to add new ones from users.

**Comment by fruitfly1026** [comment]
This is wonderful! I'll try this out then let you know.

**Comment by ShadenSmith** [comment]
@jeewhanchoi: there's a section on types, etc. in the parser's `README.md` and an open issue about extending the type system to tensor values.

**Pull request merged**
